// APP FUNDAMENTALS
export const APP_LOADING = "APP_LOADING"
export const APP_LOADED = "APP_LOADED"

export const PAGE_TRANSITION_START = "PAGE_TRANSITION_START"
export const PAGE_TRANSITION_END = "PAGE_TRANSITION_END"

// --> Header Control
export const HEADER_ACTIVE = "HEADER_ACTIVE"
export const HEADER_INACTIVE = "HEADER_INACTIVE"
